## Importing NumPy

In [1]:
import numpy as np
print("numpy.__version__:", np.__version__)

numpy.__version__: 1.13.3


## Arrays

The basic datastructure in numpy is an `ndarray`, a class encapsulating a contiguous block of data, containing multiple elements (like the Python `list` data structure).

In [2]:
v = np.array([1,2,3,4,5])
print(type(v))
v

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

Whereas, Python lists can be heterogeneous:

In [3]:
# A python array
a = [1.0,2,3.0,"4"]
print(type(a))
a

<class 'list'>


[1.0, 2, 3.0, '4']

## Initializing arrays from Python lists
NumPy arrays can be created from Python lists. All elements in an `ndarray` have to be the same type (numpy will upcast where possible):

In [4]:
# A numpy ndarray
np.array([1.0,2,3.0,4])

array([ 1.,  2.,  3.,  4.])

We can explicitly specify the type of the elements (the `dtype`) of a `ndarray`.

In [5]:
np.array([1,2,3,4], dtype="float32")

array([ 1.,  2.,  3.,  4.], dtype=float32)

The `dtype` argument can be a string (an internal numpy data type) or a Python built-in type:

In [6]:
np.array([1,2,3,4], dtype=float)

array([ 1.,  2.,  3.,  4.])

Numpy arrays can be multi-dimensional, and can be constructed via Python list-of-lists:

In [7]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Note the difference: `a` is a one-dimensional array, and `b` is a two dimensional array:

In [8]:
a = np.array([i for i in range(3)])
b = np.array([[i] for i in range(3)])

from pprint import pprint
print("a = "); pprint(a)
print("b = "); pprint(b)

a = 
array([0, 1, 2])
b = 
array([[0],
       [1],
       [2]])


## Initializing arrays from scratch
It can be more efficient to use the numpy package method to initialize arrays, especially large ones, without having to create an intermediate Python list. `numpy` contains a number of functions to do this.

In [9]:
# Create an array filled with zeroes
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Create a 2 dimensional array (3x5) filled with ones
np.ones((3,5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
# Create an 2 dimensional array filled with a single number
np.full((3,5), 3.14159)

array([[ 3.14159,  3.14159,  3.14159,  3.14159,  3.14159],
       [ 3.14159,  3.14159,  3.14159,  3.14159,  3.14159],
       [ 3.14159,  3.14159,  3.14159,  3.14159,  3.14159]])

In [12]:
# Create a single-dimensional array (a vector) filled with a linear sequence:
np.arange(3), np.arange(2,5.), np.arange(1,10,4)

(array([0, 1, 2]), array([ 2.,  3.,  4.]), array([1, 5, 9]))

In [13]:
# Generate a number of values within an interval (e.g., 5 values between 0. and 1.)
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [14]:
# Create a 3x5 array of uniformly distributed random values between 0 and 1
np.random.random((3, 5))

array([[ 0.92255706,  0.48366334,  0.47866763,  0.34179756,  0.43868368],
       [ 0.98300915,  0.75973829,  0.38357387,  0.14244424,  0.00898861],
       [ 0.14835698,  0.82355018,  0.33766153,  0.05875616,  0.17800879]])

In [15]:
# Create a 3x5 array of normally distributed random values, with mean 0 and std 1
np.random.normal(0., 1., (3, 5))

array([[ 0.30246066,  0.91764933,  0.93091472,  1.24034179, -0.30107068],
       [-0.36521874,  2.44564768, -2.17230966,  0.44238252,  0.9150405 ],
       [ 0.61636086, -1.29281959,  0.89521347,  1.39831463,  1.19346925]])

In [16]:
# Create a 3x5 array of uniformally random integers in the half-open interval [0, 10]
np.random.randint(0, 10, (3, 5))

array([[5, 9, 3, 3, 3],
       [2, 3, 2, 2, 7],
       [2, 0, 2, 2, 2]])

In [17]:
# Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [18]:
# Create an unitialized array of 3 integers (filled with garbage)
np.empty(3)

array([ 1.,  1.,  1.])

## Creating new arrays with the same shape as another array

In [95]:
M = np.random.randint(0, 10, (3, 5))
M

array([[1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3],
       [6, 7, 2, 0, 3]])

In [97]:
np.zeros_like(M)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [98]:
np.ones_like(M)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Standard data types

numpy suppots a variety of numeric types, similar to C or Fortran.  You can specify the type as a string or a numpy object.  For some types, you can use Python's built in types.

In [19]:
[
    "bools",
    np.ones(1, dtype=np.bool_),
    np.ones(1, dtype=bool), # Python type
    np.ones(1, dtype="bool_"),
    "------------",
    "default int (signed)",
    np.ones(1, dtype=np.int_), # Default integer type, same as C `long`, either `int64` or `int32`
    np.ones(1, dtype=int), # Python type
    np.ones(1, dtype="int_"),
    "------------",
    "C `int` (signed)",
    np.ones(1, dtype=np.intc), # Same as C int, either `int32` or `int64`
    np.ones(1, dtype="intc"),
    "------------",
    "Integer used for indexing (C `ssize_t`, the size of a pointer)",
    np.ones(1, dtype=np.intp),
    np.ones(1, dtype="intp"),
    "------------",
    "Signed Integers of various fixed sizes",
    np.ones(1, dtype=np.int8),
    np.ones(1, dtype="int8"),
    np.ones(1, dtype=np.int16),
    np.ones(1, dtype="int16"),
    np.ones(1, dtype=np.int32),
    np.ones(1, dtype="int32"),
    np.ones(1, dtype=np.int64),
    np.ones(1, dtype="int64"),
    "------------",
    "Unsigned integers of various fixed sizes",
    np.ones(1, dtype=np.uint8),
    np.ones(1, dtype="uint8"),
    np.ones(1, dtype=np.uint16),
    np.ones(1, dtype="uint16"),
    np.ones(1, dtype=np.uint32),
    np.ones(1, dtype="uint32"),
    np.ones(1, dtype=np.uint64),
    np.ones(1, dtype="uint64"),
    "------------",
    "Floating point types",
    np.ones(1, dtype=np.float16),
    np.ones(1, dtype="float16"),
    np.ones(1, dtype=np.float32),
    np.ones(1, dtype="float32"),
    np.ones(1, dtype=np.float_), # Same as float64
    np.ones(1, dtype="float_"),
    np.ones(1, dtype=np.float64),
    np.ones(1, dtype="float64"),
    "------------",
    "Complex number types",
    np.ones(1, dtype=np.complex64), # two 32-bit floats
    np.ones(1, dtype="complex64"),
    np.ones(1, dtype=np.complex128), # two 64-bit floats
    np.ones(1, dtype="complex128"),
    np.ones(1, dtype=np.complex_), # Same as complex128
    np.ones(1, dtype="complex_"),
]

['bools',
 array([ True], dtype=bool),
 array([ True], dtype=bool),
 array([ True], dtype=bool),
 '------------',
 'default int (signed)',
 array([1]),
 array([1]),
 array([1]),
 '------------',
 'C `int` (signed)',
 array([1], dtype=int32),
 array([1], dtype=int32),
 '------------',
 'Integer used for indexing (C `ssize_t`, the size of a pointer)',
 array([1]),
 array([1]),
 '------------',
 'Signed Integers of various fixed sizes',
 array([1], dtype=int8),
 array([1], dtype=int8),
 array([1], dtype=int16),
 array([1], dtype=int16),
 array([1], dtype=int32),
 array([1], dtype=int32),
 array([1]),
 array([1]),
 '------------',
 'Unsigned integers of various fixed sizes',
 array([1], dtype=uint8),
 array([1], dtype=uint8),
 array([1], dtype=uint16),
 array([1], dtype=uint16),
 array([1], dtype=uint32),
 array([1], dtype=uint32),
 array([1], dtype=uint64),
 array([1], dtype=uint64),
 '------------',
 'Floating point types',
 array([ 1.], dtype=float16),
 array([ 1.], dtype=float16),
 arr

## Array attributes

In [20]:
np.random.seed(0)
x1 = np.arange(10) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4), dtype=np.uint8) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5), dtype=np.int16)

print("x1: ndim:", x1.ndim, "shape:", x1.shape, "size:", x1.size, "dtype:", x1.dtype)
print("x2: ndim:", x2.ndim, "shape:", x2.shape, "size:", x2.size, "dtype:", x2.dtype)
print("x3: ndim:", x3.ndim, "shape:", x3.shape, "size:", x3.size, "dtype:", x3.dtype)

print("x3.itemsize:", x3.itemsize, "bytes; x3.nbytes=", x3.nbytes, "bytes")

x1: ndim: 1 shape: (10,) size: 10 dtype: int64
x2: ndim: 2 shape: (3, 4) size: 12 dtype: uint8
x3: ndim: 3 shape: (3, 4, 5) size: 60 dtype: int16
x3.itemsize: 2 bytes; x3.nbytes= 120 bytes


## Array indexing

In [21]:
print("x1:", x1)
print("x1[0]:", x1[0])
print("x1[4]:", x1[4])
print("x1[-1]:", x1[-1])
print("x1[-2]:", x1[-2])
print()
print("x2:", x2)
print("x2[2,-2]:", x2[2,-2])
# Assignment
x2[2,-2] = 314.159 # Silent truncation of float to dtype of array
print("x2[2,-2]:", x2[2,-2]) # 314 % 256 == 58

x1: [0 1 2 3 4 5 6 7 8 9]
x1[0]: 0
x1[4]: 4
x1[-1]: 9
x1[-2]: 8

x2: [[4 7 5 6]
 [6 7 0 1]
 [8 3 3 2]]
x2[2,-2]: 3
x2[2,-2]: 58


## Array slicing
The array slice syntax is `array[start:stop:step]`, where `start` defaults to `0` if omitted, `stop` defaults to *size of array* if omitted, and `step` defaults to `1`.

In [22]:
x1[:5]

array([0, 1, 2, 3, 4])

In [23]:
x1[5:]

array([5, 6, 7, 8, 9])

In [24]:
x1[4:7]

array([4, 5, 6])

In [25]:
x1[::2] # Every other element

array([0, 2, 4, 6, 8])

In [26]:
x1[1::2] # Every other element, starting at index 1

array([1, 3, 5, 7, 9])

When the step value is negative, the defaults for `start` and `stop` are swapped and the array is traversed in reverse.

In [27]:
x1[::-1] # All elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
x1[5::-2]  # == x1[0:5] reversed, every other element

array([5, 3, 1])

Multidimensional slices are separated by commas:

In [29]:
print("x2:", x2)
print("x2[:2, :3]", x2[:2, :3]) # Two rows, three columns

x2: [[ 4  7  5  6]
 [ 6  7  0  1]
 [ 8  3 58  2]]
x2[:2, :3] [[4 7 5]
 [6 7 0]]


In [30]:
print("x2[:, ::2]", x2[:, ::2]) # All rows, every other column

x2[:, ::2] [[ 4  5]
 [ 6  0]
 [ 8 58]]


In [31]:
print("x2[::-1, :]\n", x2[::-1, :]) # First dimension reversed

x2[::-1, :]
 [[ 8  3 58  2]
 [ 6  7  0  1]
 [ 4  7  5  6]]


Accessing a single row:

In [32]:
print(x2[:, 2]) # Third column of x2

[ 5  0 58]


In [33]:
print(x2[1, :]) # Second row of x2

[6 7 0 1]


In [34]:
print(x2[1]) # Row slices: the empty (column) slice can be omitted

[6 7 0 1]


## Slices are no-copy, writable views

In [35]:
print(x2)

[[ 4  7  5  6]
 [ 6  7  0  1]
 [ 8  3 58  2]]


In [36]:
x2_sub = x2[1:, 2:]
print(x2_sub)

[[ 0  1]
 [58  2]]


In [37]:
x2_sub[0, 0] = 255
print(x2_sub)

[[255   1]
 [ 58   2]]


In [38]:
print(x2)

[[  4   7   5   6]
 [  6   7 255   1]
 [  8   3  58   2]]


## Copying slices

When it is required, the `copy()` method can be used to explicitly copy the data within an array or slices.

In [39]:
x2_sub_copy = x2[1:, 2:].copy()
x2_sub_copy[0, 0] = 0
print(x2_sub_copy)
print(x2)

[[ 0  1]
 [58  2]]
[[  4   7   5   6]
 [  6   7 255   1]
 [  8   3  58   2]]


## Reshaping arrays
The `reshape()` method can change the dimensions of an array, as long as the *size* of the initial and the reshaped array are the same.  This will avoid copying where possible, but cannot be guaranteed if the memory buffers are non-contiguous.

In [40]:
vector = np.arange(1, 10)
print(vector) # 9 elements
matrix = vector.reshape(3, 3) # 9 elements
print(matrix)
matrix[0, 0] = 1000 # no-copy slice, so modifies the original vector
print(vector)

matrix2 = matrix[::2] # first and third row, 6 elements, 2x3 matrix
print(matrix2)
matrix2[1, 0] = 999  # Still a no-copy slice, so will modify the original vector
print(vector)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1000    2    3    4    5    6    7    8    9]
[[1000    2    3]
 [   7    8    9]]
[1000    2    3    4    5    6  999    8    9]


A common use case is to convert a one-dimensional vector into a two-dimensional column or row vector. This can be done by `reshape()` as well.

In [41]:
vector = np.arange(1, 4) # a vector of size 3
print(vector) # one-dimensional vector, size 3
print(vector.reshape((1, 3))) # 2-dimensional row matrix, 1x3
print(vector.reshape((3, 1))) # 2-dimensional column matrix, 3x1

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


But it can be more convenient (and clearer) to introduce the new axis using the `np.newaxis` keyword.

In [42]:
print(vector[np.newaxis, :]) # Introduces a new first (row) dimension, making it a row matrix
print(vector[:, np.newaxis]) # Introduces a new second (column) dimensino, making it a column matrix

[[1 2 3]]
[[1]
 [2]
 [3]]


## Concatenation of arrays
The `concatenate()` function can combine multiple arrays at once.  The arrays are provided in a list.

In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print(np.concatenate([a, b, c]))

[1 2 3 4 5 6 7 8 9]


Multi-dimensional arrays can also be concatenated. `concatenate()` takes an optional argument, `axis` that defaults to 0, telling it which axis or dimension to concatenate.  Axes are 0-indexes (that is, the rows are axis `0`, columns are axis `1`, etc.)

In [44]:
d = np.array([[1,2,3], [4,5,6]])
e = np.array([[100,200,300], [400,500,600]])
print(np.concatenate([d, e], axis=0)) # concat the rows

[[  1   2   3]
 [  4   5   6]
 [100 200 300]
 [400 500 600]]


In [45]:
print(np.concatenate([d, e], axis=1)) # concatenate the columns

[[  1   2   3 100 200 300]
 [  4   5   6 400 500 600]]


This can be clearer using the `vstack()` (vertical stack) and `hstack()` functions.

In [46]:
print(np.vstack([d, e]))

[[  1   2   3]
 [  4   5   6]
 [100 200 300]
 [400 500 600]]


In [47]:
print(np.hstack([d, e]))

[[  1   2   3 100 200 300]
 [  4   5   6 400 500 600]]


If the arrays are 3-dimensional, they can also be concatenated in the third axis using `dstack()`.

## Splitting arrays
The functions `split()`, `hsplit()`, `vsplit()`, `dsplit()` can split arrays.  They take a list of *N* indices as split points, and produce *N+1* slices. `split()` takes an argument `axis` (defaults to `0`) denoting the dimension to split, with `0` being rows, `1` being columns, and so on. `vsplit()` is equivalent to `split()` with axis `0`, `vsplit` is equivalent to `split()` with axis `1` and so on.

In [48]:
f = np.arange(16).reshape(4, 4) # 4x4 matrix
print(f)
g, h, k = np.vsplit(f, [1, 3]) # split vertically (by rows)
print(g)
print(h)
print(k)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [49]:
g, h, k = np.hsplit(f, [1, 3]) # split horizontally (by columns)
print(g)
print(h)
print(k)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [50]:
g, h, k = np.split(f, [1, 3], axis=1) # Equivalent of hsplit
print(h)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]



## Universal functions or *ufuncs*
NumPy has built-in methods and functions that perform vectorized operations on arrays.

### Arithmetic *ufuncs*
NumPy has the equivalent of standard Python arithmetic operators.  They can be invoked as numpy functions, or standard Python operators (which call the ufunc behind the scenes).

In [51]:

x = np.arange(4)
print("x    =", x)
print("x + 5  =", x + 5) # or np.add(x, 5)
print("x - 5  =", x - 5) # np.subtract
print("x * 2  =", x * 2) # np.multiply
print("x / 2  =", x / 2) # np.divide
print("x // 2 =", x // 2) # np.floor_divide
print("x ** 2 =", x ** 2) # np.power
print("-x     =", -x) # np.negative
print("x % 2  =", x % 2) # np.mod
print("abs(x - 2) =", abs(x - 2)) # np.absolute aka np.abs

x    = [0 1 2 3]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 2  = [0 2 4 6]
x / 2  = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]
-x     = [ 0 -1 -2 -3]
x % 2  = [0 1 0 1]
abs(x - 2) = [2 1 0 1]


### Trigonometric *ufuncs*

In [52]:
theta = np.linspace(0, np.pi, 4)
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))
y = np.cos(theta)
print("arccos(y) =", np.arccos(y))

theta      = [ 0.          1.04719755  2.0943951   3.14159265]
sin(theta) = [  0.00000000e+00   8.66025404e-01   8.66025404e-01   1.22464680e-16]
cos(theta) = [ 1.   0.5 -0.5 -1. ]
tan(theta) = [  0.00000000e+00   1.73205081e+00  -1.73205081e+00  -1.22464680e-16]
arccos(y) = [ 0.          1.04719755  2.0943951   3.14159265]


### Exponential *ufuncs*

In [53]:
x = np.array([1, 2, 3])
print("x        =", x)
print("e^x      =", np.exp(x))
print("2^x      =", np.exp2(x))
print("3^x      =", np.power(3, x))
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1 2 3]
e^x      = [  2.71828183   7.3890561   20.08553692]
2^x      = [ 2.  4.  8.]
3^x      = [ 3  9 27]
ln(x)    = [ 0.          0.69314718  1.09861229]
log2(x)  = [ 0.         1.         1.5849625]
log10(x) = [ 0.          0.30103     0.47712125]


Specialized exponential and log function versions useful for maintaining precision with very small inputs:

In [54]:
x = np.array([0, 0.00001, 0.01, 0.1])
print("x =", x)
print("e^x - 1 =", np.exp(x) - 1)
print("e^x - 1 =", np.expm1(x))
print("log(1 + x) =", np.log(1 + x))
print("log(1 + x) =", np.log1p(x))

x = [  0.00000000e+00   1.00000000e-05   1.00000000e-02   1.00000000e-01]
e^x - 1 = [  0.00000000e+00   1.00000500e-05   1.00501671e-02   1.05170918e-01]
e^x - 1 = [  0.00000000e+00   1.00000500e-05   1.00501671e-02   1.05170918e-01]
log(1 + x) = [  0.00000000e+00   9.99995000e-06   9.95033085e-03   9.53101798e-02]
log(1 + x) = [  0.00000000e+00   9.99995000e-06   9.95033085e-03   9.53101798e-02]


### Comparison *ufuncs*
Elements of arrays can be compared to a value, resulting an equal sized array with boolean values. The following comparison operators are available:

| Operator | Equivalent ufunc |
|:--- |:--- |
| `==` | `np.equal` |
| `!=` | `np.not_equal` |
| `<` | `np.less` |
| `<=` | `np.less_equal` |
| `>` | `np.greater` |
| `>=` | `np.greater_equal` |

In [55]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [56]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]], dtype=bool)

Two arrays can be compared element-wise.

## *ufuncs* on two arrays
Binary ufuncs support both arguments being arrays.

In [57]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x * y)

[ 4 10 18]


In [58]:
(2 * x) == (x ** 2)

array([False,  True, False], dtype=bool)

## Storing ufunc outputs in existing memory locations
If the result of some calculation needs to be stored in an existing array, it can be more efficient to specify the location where the output should be stored, via the `out` parameter to numpy functions.

In [59]:
x = np.arange(5)
y = np.zeros(5)
np.multiply(x, 10, out=y)
print(y)

[  0.  10.  20.  30.  40.]


A slice can be specified as well.

In [60]:
y = np.zeros(10)
np.power(2, x, out=y[::2]) # Store result in every other location in y
print(y)

[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


The above is more memory efficient that `y[[::2] = 2 ** x`.

## Aggregating ufuncs

In [61]:
M = np.random.random((3, 4))
print(M)
print(M.min(), M.max(), M.sum()) # or np.min(M), np.max(M), np.sum(M)
print(M.sum(axis=0)) # sum traverses rows, i.e., sums up columns
print(M.sum(axis=1)) # sum traverses columns, i.e., sums up rows

[[ 0.58201979  0.53737323  0.75861562  0.10590761]
 [ 0.47360042  0.18633234  0.73691818  0.21655035]
 [ 0.13521817  0.32414101  0.14967487  0.22232139]]
0.105907607188 0.758615624322 4.42867298389
[ 1.19083838  1.04784658  1.64520867  0.54477935]
[ 1.98391625  1.61340129  0.83135544]


## General aggregation of elements on an array
Any binary ufunc can be applied to pairs of elements of an array along a given axis using `reduce`.

In [62]:
a = np.arange(1, 6, dtype=np.float_)
print(a)
print(np.add.reduce(a)) # same as np.sum(a)
print(np.multiply.reduce(a)) # same as np.prod(a)
print(np.divide.reduce(a)) # no equivalent

[ 1.  2.  3.  4.  5.]
15.0
120.0
0.00833333333333


A multi-dimensioanl example:

In [63]:
x = np.arange(8).reshape((2, 2, 2))
print(x)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [64]:
print(np.add.reduce(x)) # axis=0 by default

[[ 4  6]
 [ 8 10]]


In [65]:
print(np.add.reduce(x, axis=1))

[[ 2  4]
 [10 12]]


In [66]:
print(np.add.reduce(x, axis=2))

[[ 1  5]
 [ 9 13]]


## *Broadcasting* behaviour of binary *ufuncs*
A binary operation over two arrays will work with arrays of different sizes or dimensions under the following conditions:
1. **Rule 1.** If the two arrays differ in their number of dimensions, the *shape* of the one with fewer dimensions is *padded* with ones on its leading (i.e., *left*) side.
1. **Rule 2.** If the shape of the two arrays does not match in a given dimension, the array with shape equal to `1` in *that* dimension is *stretched* to match the other shape.
1. **Rule 3.** If in any dimension the sizes disagree and neither is equal to `1`, an error is raised.

### E.g.: adding a scalar to a one-dimensional array

In [67]:
a = np.arange(3)
print("a.shape = ", a.shape)
print("a =", a)
b = 5
a + b

a.shape =  (3,)
a = [0 1 2]


array([5, 6, 7])

1. **Rule 1.** Here, the shape of `a` is `(3,)` and `b` has no shape as it is a scalar.  By **Rule 1** `b`'s shape is padded with `1`. It becomes `[5]` with shape `(1,)`.
1. **Rule 2.** Since `a`'s shape (`(3,)`) and `b`'s new shape (`(1,)`) do not match in the first dimension (axis `0`), by **Rule 2**, the one with shape equal to `1` in that dimension (that is, `b`) is *stretched* and it becomes `[5 5 5]` and its shape is now `(3,)`.
1. Since the shapes and sizes of the arrays match now, their elements are added pairwise and we get the result above.

### E.g.: adding a two-dimensional array to a one-dimensional array

In [68]:
a = np.ones((2,3))
print("a.shape =", a.shape)
print("a =\n" + str(a))
b = np.arange(3)
print("b.shape =", b.shape)
print("b =", b)
print("a + b =\n" + str(a + b))

a.shape = (2, 3)
a =
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
b.shape = (3,)
b = [0 1 2]
a + b =
[[ 1.  2.  3.]
 [ 1.  2.  3.]]


1. **Rule 1.** Here, the shape of `a` is `(2,3)` and `b`s shape is `(3,)`. `b`'s shape has fewer dimensions than `a`'s shape. It becomes `[[0 1 2]]` with shape `(1,3)`.
1. **Rule 2.** Since `a`'s shape (`(2,3)`) and `b`'s new shape (`(1,3)`) do not match in the first dimension (axis `0`), by **Rule 2**, the one with shape equal to `1` in that dimension (that is, `b`) is *stretched* in that dimension and it becomes `[[0 1 2], [0 1 2]]` and its shape becomes `(2,3)`.
1. The arrays shapes and dimensions match, so their elements are added pairwise leading to the result above.

### E.g.: both arrays broadcasted

In [69]:
a = np.ones((3,1))
b = np.ones(3)
print("a.shape =", a.shape)
print("a =")
print(a)
print("b.shape =", b.shape)
print("b =")
print(b)
print("a + b =")
print(a + b)

a.shape = (3, 1)
a =
[[ 1.]
 [ 1.]
 [ 1.]]
b.shape = (3,)
b =
[ 1.  1.  1.]
a + b =
[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


1. **Rule 1.** Here, the shape of `a` is `(3,1)` and `b`s shape is `(3,)`. `b`'s shape has fewer dimensions than `a`'s shape. It becomes `[[1 1 1]]` with shape `(1,3)`.
1. **Rule 2.** Since `a`'s shape (`(3,1)`) and `b`'s new shape (`(1,3)`) do not match in the second dimension (axis `1`), by **Rule 2**, the one with shape equal to `1` in that dimension (that is, `b`) is *stretched* in that dimension and it becomes `[[1 1 1], [1 1 1]]` and it's shape becomes `(3,3)`.
1. **Rule 2.** Now, the shape of `a` is `(3,1)` and `b`'s new shape is `(3,3)`. Since `a`'s shape and `b`'s shape do not match in the second dimension (axis `1`), the one with shape equal to `1` in that dimension (that is, `a`) is *stretched* in that dimension, and it becomes `[[1 1 1], [1 1 1], [1 1 1]]` and its shape becomes `(3,3)`.
1. The arrays shapes and dimensions match, so their elements are added pairwise leading to the result above.

### E.g.: Arrays are not compatible

In [70]:
a = np.ones((3,2))
b = np.arange(3)
print("a.shape =", a.shape)
print("a =")
print(a)
print("b.shape =", b.shape)
print("b =")
print(b)
print("a + b =")
print(a + b)

a.shape = (3, 2)
a =
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
b.shape = (3,)
b =
[0 1 2]
a + b =


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

1. **Rule 1.** Here, the shape of `a` is `(3,2)` and `b`s shape is `(3,)`. `b`'s shape has fewer dimensions than `a`'s shape. It becomes `[[0 1 2]]` with shape `(1,3)`.
1. **Rule 2.** Since `a`'s shape (`(3,2)`) and `b`'s new shape (`(1,3)`) do not match in the first dimension (axis `0`), by **Rule 2**, the one with shape equal to `1` in that dimension (that is, `b`) is *stretched* in that dimension and it becomes `[[1 1 1], [1 1 1], [1 1 1]]` and it's shape becomes `(3,3)`.
1. **Rule 3.** Now the shape of `a` is `(3,2)` and b's shape is `(3,3)'.  Rule 1 does not apply as both have the same number of dimensions. Rule 2 also does not apply because although the two arrays don't have the same shape in the second dimension (axis `1`), neither of them have a value of `1` in that dimension and cannot be stretched. Hence the arrays do not have the same shape and nothing more can be done. An error is raised.

## *ufuncs* that work with boolean arrays
Several NumPy functions work with arrays of booleans.

In [75]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

We can do elementwise comparison on elements and produce an array of booleans.

In [82]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]], dtype=bool)

How many values less than 6?

In [76]:
np.count_nonzero(x < 6) # False is treated as 0

8

Are any values greater than 8?

In [78]:
np.any(x > 8)

True

Are all values less than 10?

In [79]:
np.all(x < 10)

True

`all()` and `any()` can work on specific axes.  E.g., which rows have at least one value greater than 5?

In [81]:
np.any(x > 5, axis=1)

array([False,  True,  True], dtype=bool)

## Boolean operators
NumPy has functions that perform logical operations on boolean arrays.  They are actually bitwise-arithmetic operators, that treat `False` as `0` and `True` as `1`, but can also work on numeric values.

Operator | Equivalent ufunc
--- | ---
`&` | `np.bitwise_and`
<code>&#124;</code> | `np.bitwise_or`
`^` | `np.bitwise_xor`
`~` | `np.bitwise_not`


In [83]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [88]:
(x < 6) & (x > 2)

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [False,  True, False, False]], dtype=bool)

## Boolean arrays as *masks*
We can use a boolean array to select only those elements from a source array that correspond to a `True` value in the boolean array.  The returned value is a single dimensional array (row vector).

In [89]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [92]:
y = x < 6
y

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]], dtype=bool)

To select only those values from `x` where `x > 6` is `True`, we have to use the boolean array as an index.

In [94]:
x[y] # Or simply, x[x < 6]

array([5, 0, 3, 3, 3, 5, 2, 4])

## Fancy indexing
Array indices need not only be integers.  They can be arrays as well.  This is *fancy* indexing.

In [102]:
a = np.random.randint(10, size=(10))
a

array([9, 4, 4, 6, 4, 4, 3, 4, 4, 8])

In [105]:
idx = np.array([1,5,6])
a[idx]

array([4, 4, 3])

Indexes can be multi-dimensional. The returned value has the shape of the **index** and not the source array.

In [110]:
idx = np.array([[1,2],[3,4]])
a[idx] # indexing into a one-dimensional array with a two-dimensional index

array([[4, 4],
       [6, 4]])

We can combine integer indexes or slices with *fancy* indexes.

In [108]:
M = np.arange(1,10).reshape((3,3))
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
M[1:, np.array([2,1])]

array([[6, 5],
       [9, 8]])

### Use case: selecting random points
Here we have an array representing 100 2-dimensional points.

In [114]:
mean = [0, 0]; cov = [[1, 2], [2,5]]
X = np.random.multivariate_normal(mean, cov, 100)
X.shape

(100, 2)

We can pull out 10 distinct random points like so:

In [115]:
idx = np.random.choice(X.shape[0], 10, replace=False)
idx

array([99, 60, 36, 31, 90,  2, 61, 18, 45, 12])

In [117]:
selection = X[idx]
selection.shape

(10, 2)

### Assigning with fancy indexing
Fancy indexing can be used to modify parts of an array (just as with integer or slice indexes).  But there are gotchas if some indexes repeat.

In [118]:
# Simple case, non-reperating indexes
x = np.arange(10)
idx = np.array([2,1,8,4])
x[idx] = 99
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [119]:
# Simple case, non-repeating indexes, in-place mutation (or what looks like it)
x = np.arange(10)
idx = np.array([2,1,8,4])
x[idx] -= 10
x

array([ 0, -9, -8,  3, -6,  5,  6,  7, -2,  9])

What if the indexes repeated in the above operation?  Would `-10` be applied to repeated index multiple times?

In [126]:
x = np.arange(10)
idx = np.array([2,2,8,4])
x[idx] -= 10
x

array([ 0,  1, -8,  3, -6,  5,  6,  7, -2,  9])

It looks like `-10` was applied to `x[2]` only once.

This is because, `a[i] -= b` is translated to `a[i] = a[i] - b`.  `a[i] - b` is evaluated first, twice, getting the same value (`x[2] - 10 -> -8`). Then the value is put in the location `a[i]`. So the same value ends up getting assigned twice.

Another example:

In [123]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
x

array([ 6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

It looks like only the value `6` was assigned.  Actually, though, first the value `4` was assigned to `x[0]`, and then the value `6` was assigned to `x[0]` again, over-writing the previous value.

### Assigning to a repeated index, with repeated application
What if we wanted `-10` to really be applied to a location as many times as an index showed up? We can use the `at` modifier to NumPy *ufuncs* for this.

In [125]:
x = np.arange(10)
idx = np.array([2,2])
np.subtract.at(x, idx, 10)
x

array([  0,   1, -18,   3,   4,   5,   6,   7,   8,   9])

## Sorting

In [127]:
x = np.array([2,1,4,3,5])
x

array([2, 1, 4, 3, 5])

In [128]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [129]:
np.argsort(x) # Instead of getting a new sorted array, get the indexes of the values in sorted order

array([1, 0, 3, 2, 4])

In [130]:
x = np.random.randint(0, 10, (4, 6))
x

array([[6, 6, 4, 1, 5, 4],
       [5, 5, 6, 3, 8, 1],
       [4, 2, 9, 7, 4, 1],
       [8, 2, 3, 3, 4, 1]])

In [131]:
# sort columns
np.sort(x, axis=0)

array([[4, 2, 3, 1, 4, 1],
       [5, 2, 4, 3, 4, 1],
       [6, 5, 6, 3, 5, 1],
       [8, 6, 9, 7, 8, 4]])

In [132]:
# sort rows
np.sort(x, axis=1)

array([[1, 4, 4, 5, 6, 6],
       [1, 3, 5, 5, 6, 8],
       [1, 2, 4, 4, 7, 9],
       [1, 2, 3, 3, 4, 8]])

## K-smallest values
The `partition` function splits an array into *K* smalles values, and the remainder.

In [134]:
x = np.array([7,2,3,1,6,5,4])
np.partition(x, 2) # smalles 2 values to the left of the partition, rest to the right

array([1, 2, 3, 7, 6, 5, 4])

Note that the resulting array is not sorted. It just gurantess that the first `K` values are the smallest
`K` values in the array.  Within the two partitions, the elements can have random order.

## Compound data types

In [156]:
data = np.zeros(4, dtype=np.dtype([ ('name', 'U10'), ('age', 'i4'), ('weight', 'f8') ]))

names    = ['Bob', 'Alice', 'Diana', 'Susan']
ages     = [ 32,    23,      43,      19]
weights  = [ 85.,   55.,     65.,     37]

data['name']   = names
data['age']    = ages
data['weight'] = weights

data

array([('Bob', 32,  85.), ('Alice', 23,  55.), ('Diana', 43,  65.),
       ('Susan', 19,  37.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [157]:
data[0]

('Bob', 32,  85.)

In [158]:
data[-1]['name']

'Susan'

In [159]:
data[data['age'] > 40]['name']

array(['Diana'],
      dtype='<U10')

### More advanced compound data types
Here is a data type with an integer field named `id` and a 3x3 matrix valued field named `mat`.

In [151]:
tp = np.dtype([ ('id', 'i4'), ('mat', 'f8', (3,3))])
tp

dtype([('id', '<i4'), ('mat', '<f8', (3, 3))])

In [152]:
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[ 0.,  0.,  0.], [ 0.,  0.,  0.], [ 0.,  0.,  0.]])
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


### RecordArrays
`np.recarray` is a data type that allows you to access the fields of the compound data type using attributes, instead as dictionary keys.  This could be more convenient or readable.  However, it has a higher cost for accessing the data.

In [153]:
X

array([(0, [[ 0.,  0.,  0.], [ 0.,  0.,  0.], [ 0.,  0.,  0.]])],
      dtype=[('id', '<i4'), ('mat', '<f8', (3, 3))])

In [160]:
data_rec = data.view(np.recarray)
data_rec

rec.array([('Bob', 32,  85.), ('Alice', 23,  55.), ('Diana', 43,  65.),
           ('Susan', 19,  37.)], 
          dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [161]:
data_rec.age

array([32, 23, 43, 19], dtype=int32)

In [162]:
data_rec[0].name

'Bob'

As mentioned before, there is greater performance overhead in accessing the data from a recarray, even using the dictionary syntx.

In [163]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

94.8 ns ± 0.461 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
2.57 µs ± 70.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.2 µs ± 56.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
