# Importing Pandas

In [1]:
import pandas as pd
pd.__version__

'0.21.0'

# Pandas `Series` Class
A Pandas Series object is like a generalized array where the indexes are explicit, don't have to be contiguous or increasing, and in fact don't have to be integers.  The object also behaves like a specialised dictionary where the keys are in order (though not necessarily sorted).

## Implicit indexes

In [2]:
# Simple series
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.index # a pd.Index object

RangeIndex(start=0, stop=4, step=1)

In [4]:
data.values # a NumPy array

array([ 0.25,  0.5 ,  0.75,  1.  ])

## Explicit indexes
The difference between a Pandas Series and a NumPy array is that the Pandas object has an **explicit** index. Indexes need not be contiguous or even monotonic.  Here, we specify an explicit index which are not contiguous or uniformly increasing. Series will preserve the order in which we specified the index.

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2,5,3,7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [6]:
data.index

Int64Index([2, 5, 3, 7], dtype='int64')

### Explicit, Non-integer indexes

Any data type can be used as an index.

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

We can construct a Series object directly from a Python dictionary. The dict's keys will be the Series' index. The dict's keys will be **sorted**.  Note below: `Indonesia` comes before `USA` in the Series.

In [9]:
pop_dict = {'China': 13888170000,
            'India': 1325460000,
            'USA': 326309000,
            'Indonesia': 261890900}
pop = pd.Series(pop_dict)
pop

China        13888170000
India         1325460000
Indonesia      261890900
USA            326309000
dtype: int64

In [10]:
pop['China']

13888170000

## Constructing Series

In [11]:
# From a list
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [12]:
# From a scalar, repeated to fill the specified index
pd.Series(10, index=[100, 200, 300])

100    10
200    10
300    10
dtype: int64

In [13]:
# From a dictionary, indexes are sorted dictionary keys
pd.Series({2:'a', 1:'b', 3:'c'})

1    b
2    a
3    c
dtype: object

In [14]:
# Index can be explicitly set with a dictionary
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3,2]) # Note: indexes in order as specified, not sorted

3    c
2    a
dtype: object

# Pandas `DataFrame` Class

A Pandas DataFrame is like a generalized two-dimensional matrix, where the row indices are flexible like a Series and column have names. It can be thought of a a collection of Series objects, which have a shared index.

In [15]:
pop_dict = {'China': 13888170000,
            'India': 1325460000,
            'USA': 326309000,
            'Indonesia': 261890900}
pop = pd.Series(pop_dict)
pop

China        13888170000
India         1325460000
Indonesia      261890900
USA            326309000
dtype: int64

In [16]:
area_dict = {'China': 9596960,
             'India': 3287590,
             'Indonesia': 1905000,
             'USA': 9631418}
area = pd.Series(area_dict)
area

China        9596960
India        3287590
Indonesia    1905000
USA          9631418
dtype: int64

In [17]:
countries = pd.DataFrame({'pop': pop, 'area': area})
countries

area          pop
China      9596960  13888170000
India      3287590   1325460000
Indonesia  1905000    261890900
USA        9631418    326309000

In [18]:
countries.index

Index(['China', 'India', 'Indonesia', 'USA'], dtype='object')

In [19]:
countries.columns

Index(['area', 'pop'], dtype='object')

In [20]:
countries.values

array([[    9596960, 13888170000],
       [    3287590,  1325460000],
       [    1905000,   261890900],
       [    9631418,   326309000]])

### DataFrame as a specialized dictionary
A DataFrame also behaves like a dictionary.  Its keys are *column names*.  This is different from a numpy array, where `data[0]` would return the first row.  In a DataFrame you index by columns: `data['colname']`.

In [21]:
countries['area']

China        9596960
India        3287590
Indonesia    1905000
USA          9631418
Name: area, dtype: int64

In [22]:
countries['pop']

China        13888170000
India         1325460000
Indonesia      261890900
USA            326309000
Name: pop, dtype: int64

## Constructing DataFrames

In [23]:
# From a list of dicts; each element is a row
lst_dicts = [ {'a': i, 'b': i+1} for i in range(3)]
lst_dicts

[{'a': 0, 'b': 1}, {'a': 1, 'b': 2}, {'a': 2, 'b': 3}]

In [24]:
pd.DataFrame(lst_dicts)

a  b
0  0  1
1  1  2
2  2  3

In [25]:
# From a NumPy 2-dimensional array
import numpy as np
np_array = np.random.rand(3,2)
np_array

array([[ 0.77932061,  0.45144265],
       [ 0.64170475,  0.7274705 ],
       [ 0.04364313,  0.80827389]])

In [26]:
pd.DataFrame(np_array, columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.779321  0.451443
b  0.641705  0.727470
c  0.043643  0.808274

In [27]:
# From a single Series object
pd.DataFrame(area, columns=['area'])

area
China      9596960
India      3287590
Indonesia  1905000
USA        9631418

In [28]:
# From a dictionary of Series objects
pd.DataFrame({'pop': pop, 'area': area})

area          pop
China      9596960  13888170000
India      3287590   1325460000
Indonesia  1905000    261890900
USA        9631418    326309000

# Pandas `Index` Class

In [29]:
idx = pd.Index([2, 3, 5, 7, 11])
idx

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [30]:
idx[1]

3

In [31]:
idx[::3]

Int64Index([2, 7], dtype='int64')

In [32]:
(idx.size, idx.shape, idx.ndim, idx.dtype)

(5, (5,), 1, dtype('int64'))

In [33]:
# Indexes are immutable
# idx[1] = 0 ## Will raise error

### Indexes as ordered sets

In [34]:
idx1 = pd.Index([1, 3, 5, 7, 9])
idx2 = pd.Index([2, 3, 5, 7, 11])

In [35]:
idx1 & idx2 # Intersection

Int64Index([3, 5, 7], dtype='int64')

In [36]:
idx1 | idx2 # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [37]:
idx1 ^ idx2 # symmetric difference, or xor

Int64Index([1, 2, 9, 11], dtype='int64')

# Indexing `Series` and `DataFrame` objects

## Series indexing

In [38]:
data = pd.Series({'a':1, 'b':2, 'c':3}, dtype='f8')
data

a    1.0
b    2.0
c    3.0
dtype: float64

### Series as a dictionary

In [39]:
data.keys()

Index(['a', 'b', 'c'], dtype='object')

In [40]:
data['b']

2.0

In [41]:
# Series can be treated as a dictionary
data['e'] = 1.25
data

a    1.00
b    2.00
c    3.00
e    1.25
dtype: float64

In [42]:
# Series as a collection of keys
'a' in data

True

In [43]:
list(data.items()) # the list() is important; items() returns a lazy iterator

[('a', 1.0), ('b', 2.0), ('c', 3.0), ('e', 1.25)]

### Series as a one-dimensional array
Pandas style indexing.

In [44]:
data['a':'c'] # the `stop` values is included

a    1.0
b    2.0
c    3.0
dtype: float64

Python style indexing.

In [45]:
data[0:2] # the `stop` value is not inclueded

a    1.0
b    2.0
dtype: float64

In [46]:
# masking, like numpy
data[(data > 1) & (data < 2)]

e    1.25
dtype: float64

In [47]:
# fancy indexing, like numpy
data[['a', 'b']] # but you can't use a 2-d array, like [['a'], ['b']]

a    1.0
b    2.0
dtype: float64

### Explicit index or Python style index?
If the Series object has explicit *integer* indexes, then:
`data[i]` will use the explicit index, while `data[i:j]` will use Python style indexes.  This can be confusing.

In [48]:
data = pd.Series(['a', 'b', 'c', 'd', 'e'], index=[1,2,3,4,5])
data

1    a
2    b
3    c
4    d
5    e
dtype: object

In [49]:
data[1] # explicit index

'a'

In [50]:
data[1:3] # implicit, 0-based, Python style index; {1:'a'} not inclued in output because its implicit index is 0.

2    b
3    c
dtype: object

### Choosing Pandas vs NumPy indexing: `loc`, `iloc`

In [51]:
# loc always uses explicit indexes, and includes the final index value
data.loc[1:3]

1    a
2    b
3    c
dtype: object

In [52]:
# iloc always uses the position-based index, and exludes the final index value
data.iloc[1:3]

2    b
3    c
dtype: object

## DataFrame indexing

In [53]:
pop_dict = {'China': 1388817000,
            'India': 1325460000,
            'USA': 326309000,
            'Indonesia': 261890900}
pop = pd.Series(pop_dict)
area_dict = {'China': 9596960,
             'India': 3287590,
             'Indonesia': 1905000,
             'USA': 9631418}
area = pd.Series(area_dict)
data = pd.DataFrame({'pop': pop, 'area': area})
data

area         pop
China      9596960  1388817000
India      3287590  1325460000
Indonesia  1905000   261890900
USA        9631418   326309000

### DataFrame as a dictionary

DataFrame can be treated as a dictionary, mapping column names to a Series (not an array of raw values!):

In [54]:
data['area']

China        9596960
India        3287590
Indonesia    1905000
USA          9631418
Name: area, dtype: int64

In [55]:
type(data['area'])

pandas.core.series.Series

If the column names are simple strings, it can be convenient to access them as attributes:

In [56]:
data.area

China        9596960
India        3287590
Indonesia    1905000
USA          9631418
Name: area, dtype: int64

The two styles access the same underlying object:

In [57]:
data.area is data['area']

True

**Unless**, the column name is the same as a DataFrame method name. In that case, the attribute refers to the method.

In [58]:
data.pop is data['pop']

False

In [59]:
type(data.pop)

method

To be safe, at least for assignment, use the dictionary style access, otherwise you may end up over-writing a method attribute and create hard to debug bugs.

In [60]:
data['density'] = data['pop'] / data['area']
data

area         pop     density
China      9596960  1388817000  144.714264
India      3287590  1325460000  403.170712
Indonesia  1905000   261890900  137.475538
USA        9631418   326309000   33.879643

### DataFrame as a 2-dimensional array

Some array-like operations can be done on the DataFrame.

In [61]:
data.T # Transpose

China         India     Indonesia           USA
area     9.596960e+06  3.287590e+06  1.905000e+06  9.631418e+06
pop      1.388817e+09  1.325460e+09  2.618909e+08  3.263090e+08
density  1.447143e+02  4.031707e+02  1.374755e+02  3.387964e+01

But DataFrame itself is not a pure array.  For e.g., in `data[idx]`, `idx` has to be a column name. In an array, it would be the row index.

The underlying data is a NumPy array.

In [62]:
data.values

array([[  9.59696000e+06,   1.38881700e+09,   1.44714264e+02],
       [  3.28759000e+06,   1.32546000e+09,   4.03170712e+02],
       [  1.90500000e+06,   2.61890900e+08,   1.37475538e+02],
       [  9.63141800e+06,   3.26309000e+08,   3.38796426e+01]])

We can do use all indexing methods supported by NumPy on the values, but we lose the nice row and column labels.

In [63]:
data.values[0]

array([  9.59696000e+06,   1.38881700e+09,   1.44714264e+02])

In [64]:
data.values[:,1]

array([  1.38881700e+09,   1.32546000e+09,   2.61890900e+08,
         3.26309000e+08])

### Choosing Pandas vs NumPy indexing: `loc`, `iloc`

We should use the `loc` and `iloc` attributes, instead.  These will preserve row and column labels.

In [65]:
data.iloc[:3, :2]

area         pop
China      9596960  1388817000
India      3287590  1325460000
Indonesia  1905000   261890900

In [66]:
data.loc['India', :'pop']

area    3.287590e+06
pop     1.325460e+09
Name: India, dtype: float64

`iloc` and `loc` support all NumPy style indexing methods.

In [67]:
data.loc[data.density > 100, ['density', 'pop']]

density         pop
China      144.714264  1388817000
India      403.170712  1325460000
Indonesia  137.475538   261890900

### Note: indexing vs slicing/masking without `loc` or `iloc`
When indexing DataFrame directly, a single index refers to a column name

In [68]:
data['area']

China        9596960
India        3287590
Indonesia    1905000
USA          9631418
Name: area, dtype: int64

But a *slice* refers to rows:

In [69]:
data['China':'India']

area         pop     density
China  9596960  1388817000  144.714264
India  3287590  1325460000  403.170712

*Direct* masking operations also refers to rows:

In [70]:
data[data.density > 100]

area         pop     density
China      9596960  1388817000  144.714264
India      3287590  1325460000  403.170712
Indonesia  1905000   261890900  137.475538

DataFrame does not support fancy indexing directly. Use `loc` or `iloc` for that.

In [71]:
# data[[1, 2, 3]] ## will raise error

# Operations
NumPy *ufuncs* work on Pandas Series and DataFrame objects (not merely on the underlying numpy array holding the data).

## Index Preservation
Unary operations preserve the *index* and *column labels* in the output.

In [72]:
rng = np.random.RandomState(42)
# A Series
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [73]:
# A DataFrame
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [74]:
# Operation on series
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [75]:
# operation on DataFrame
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [76]:
df.mean() # axis=0 by default, that is, column-wise operation

A    6.666667
B    5.000000
C    3.333333
D    5.666667
dtype: float64

In [77]:
df.mean(axis=1) # row-wise operation

0    5.75
1    5.25
2    4.50
dtype: float64

## Index Alignment
Binary operations on Series or DataFrames *align* the indices.
### Index Alignment in Series

In [78]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662}, name='area')
pop = pd.Series({'California': 38332521, 'Texas': 26448192})
pop / area

Alaska              NaN
California          NaN
Texas         38.018739
dtype: float64

Note the row indices are the union of the indices of the two inputs.  Any index for which one or the other input does not have an entry is marked with `NaN`.  This is how missing values are handled for built-in Python operators.

In [79]:
area.index | pop.index

Index(['Alaska', 'California', 'Texas'], dtype='object')

For handling missing data differently, object methods need to be used in place of the operators.

In [80]:
pop.divide(area, fill_value=0)

Alaska         0.000000
California          inf
Texas         38.018739
dtype: float64

### Index Alignment in DataFrame

In [81]:
df1 = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=['A', 'B'], index=['a', 'b'])
df1

A   B
a  1  11
b  5   1

In [82]:
df2 = pd.DataFrame(rng.randint(0, 10, (2, 3)), columns=['B', 'A', 'C'], index=['b', 'a'])
df2

B  A  C
b  4  0  9
a  5  8  0

In [83]:
df1 + df2 # Note: indexes are aligned regardless of order, and are sorted in the output

A   B   C
a  9  16 NaN
b  5   5 NaN

Instead of using built-in Python operators, we can use equivalen Pandas methods, which gives us control on how to handle missing values.

In [84]:
df1.add(df2, fill_value=1000)

A   B       C
a  9  16  1000.0
b  5   5  1009.0

## Operations between DataFrame and Series

In [85]:
A = rng.randint(10, size=(3, 4)) # A NumPy array
A

array([[9, 2, 6, 3],
       [8, 2, 4, 2],
       [6, 4, 8, 6]])

In [86]:
A - A[0] # Operation between a 2-dimensional and 1-dimensional NumPy array

array([[ 0,  0,  0,  0],
       [-1,  0, -2, -1],
       [-3,  2,  2,  3]])

In [87]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  9  2  6  3
1  8  2  4  2
2  6  4  8  6

In [88]:
df.stack() # convert to hierarchically indexed series

0  Q    9
   R    2
   S    6
   T    3
1  Q    8
   R    2
   S    4
   T    2
2  Q    6
   R    4
   S    8
   T    6
dtype: int64

In [89]:
df - df.iloc[0] # Operation between DataFrame and Series. Note: row-wise operations

Q  R  S  T
0  0  0  0  0
1 -1  0 -2 -1
2 -3  2  2  3

In [90]:
df.subtract(df['R'], axis=0) # Column-wise operations: needs explicit method call instead of using operator

Q  R  S  T
0  7  0  4  1
1  6  0  2  0
2  2  0  4  2

In [91]:
# Different sized DataFrame and Series
halfrow = df.iloc[0, ::2]
halfrow

Q    9
S    6
Name: 0, dtype: int64

In [92]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN -2.0 NaN
2 -3.0 NaN  2.0 NaN

# Missing Data
Missing data can be handled by using Python `None`, or by `NaN` for floating point data (only).

##  `None` amd `Nan` in NumPy
Having `None` in a NumPy array means that the array's dtype is `object` and all operations will take place in Python, not in optimized native code.

In [93]:
for t in ['object', 'int32', 'float32']:
    print("dtype =", t)
    arr = np.arange(1E6, dtype=t) # create an array of type t, containing 1 million numbers
    %timeit arr.sum()

dtype = object
20.4 ms ± 197 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
dtype = int32
562 µs ± 5.84 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
dtype = float32
209 µs ± 3.13 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Some operations, especially aggregations, done't like `None` values.

In [94]:
vals1 = np.array([1, None, 5, 6])
vals1, vals1.dtype

(array([1, None, 5, 6], dtype=object), dtype('O'))

In [95]:
# vals1.sum() ## Cannot handle `None`, will raise TypeError

Arrays containing only floating point values can use the `NaN` value.

In [96]:
vals2 = np.array([1., np.nan, 5., 6.])
vals2, vals2.dtype

(array([  1.,  nan,   5.,   6.]), dtype('float64'))

Now aggregations won't throw an error, but won't contain anything useful either.

In [97]:
vals2.sum()

nan

There are `NaN` friendly versions of the aggregation methods as NumPy functions.

In [98]:
np.nansum(vals2)

12.0

In [99]:
arr1 = np.arange(1e6)
arr2 = np.arange(1e6); arr2[0] = np.nan

In [100]:
%timeit arr1.sum()

283 µs ± 3.01 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [101]:
%timeit np.nansum(arr1)

1.52 ms ± 102 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [102]:
%timeit arr2.sum() # note: will return nan

285 µs ± 5.66 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [103]:
%timeit np.nansum(arr2)

1.51 ms ± 47.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


The `NaN` friendly versions are ~5x slower.

## `None` and `NaN` in Pandas Series
Pandas will convert `None` to `NaN` if all other values are floats.

### Ints

In [104]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

Pandas will automatically typecast non-floats to floats to accomodate `NaN`s when possible.

In [105]:
pd.Series([1, 2, 3, None])

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [106]:
x = pd.Series(range(2), dtype=int)
x # Note dtype

0    0
1    1
dtype: int64

In [107]:
x[0] = None
x # Note new dtype

0    NaN
1    1.0
dtype: float64

### Bools

In [108]:
y = pd.Series([True, False, True])
y

0     True
1    False
2     True
dtype: bool

In [109]:
y[0] = None # None is treated as False, not as a missing value
y

0    False
1    False
2     True
dtype: bool

In [110]:
y[0] = np.nan # NaN is not treated as False; it is a true missing value
y

0    NaN
1    0.0
2    1.0
dtype: float64

### Objects

In [111]:
z = pd.Series(['A', 'B', 'C'])
z

0    A
1    B
2    C
dtype: object

In [112]:
z[0] = None
z

0    None
1       B
2       C
dtype: object

In [113]:
z[0] = np.nan
z

0    NaN
1      B
2      C
dtype: object

In [114]:
z.isnull()

0     True
1    False
2    False
dtype: bool

In [115]:
z.notnull()

0    False
1     True
2     True
dtype: bool

In [116]:
z.dropna()

1    B
2    C
dtype: object

In [117]:
z.fillna(value='OMG')

0    OMG
1      B
2      C
dtype: object

In [118]:
z.fillna(method='bfill') # Replace NaN's with objects from higher index

0    B
1    B
2    C
dtype: object

## `None` and `NaN` in Pandas DataFrame
DataFrame's `dropna` method has options to specify the axis, and also to specify how many values must be null for a row or col to be dropped, or how many non-null values must exist for a row or col with a null value to be preserved.

In [119]:
df = pd.DataFrame([[1,         np.nan,       np.nan],
                   [2,         np.nan,       np.nan],
                   [3,         4,            np.nan]
                ])
df

0    1   2
0  1  NaN NaN
1  2  NaN NaN
2  3  4.0 NaN

In [120]:
df.isnull()

0      1     2
0  False   True  True
1  False   True  True
2  False  False  True

In [121]:
df.dropna() # drop all rows that contain even a single NaN

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [122]:
df.dropna(axis=1) # drop columns, not rows

0
0  1
1  2
2  3

In [123]:
df.dropna(axis=1, how='all') # drop columns, if all their values are NaN

0    1
0  1  NaN
1  2  NaN
2  3  4.0

In [124]:
df.dropna(axis=1, how='any') # same as dropna(axis=1)

0
0  1
1  2
2  3

In [125]:
df.dropna(thresh=2) # drop rows with NaN, keeping those that have 2 or more non-NaN values

0    1   2
2  3  4.0 NaN

In [126]:
df.fillna(value=pd.Series([1000, 2000, 3000]))

0       1       2
0  1  2000.0  3000.0
1  2  2000.0  3000.0
2  3     4.0  3000.0

In [127]:
# df.fillna(value=pd.Series([1000, 2000, 3000]), axis=1) ## Not implemented yet

In [128]:
df2 = pd.DataFrame([[1000, 1000, 1000],
                    [2000, 2000, 2000],
                    [3000, 3000, 3000]
                   ])
df.fillna(value=df2)

0       1       2
0  1  1000.0  1000.0
1  2  2000.0  2000.0
2  3     4.0  3000.0

In [129]:
df.fillna(method='ffill', axis=1) # Fill-forward along rows

0    1    2
0  1.0  1.0  1.0
1  2.0  2.0  2.0
2  3.0  4.0  4.0

# Pandas MultiIndex: Hierarchical Indexing

In [130]:
index = pd.MultiIndex.from_product([['California', 'Texas', 'New York'], [2000, 2010]], names=['State', 'Year'])
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 2, 2, 1, 1], [0, 1, 0, 1, 0, 1]],
           names=['State', 'Year'])

In [131]:
pop = pd.Series([12345, 23456, 34567, 45678, 56789, 67890], index=index, name='Population')
pop

State       Year
California  2000    12345
            2010    23456
Texas       2000    34567
            2010    45678
New York    2000    56789
            2010    67890
Name: Population, dtype: int64

In [132]:
pop['California']

Year
2000    12345
2010    23456
Name: Population, dtype: int64

In [133]:
pop[:, 2010]

State
California    23456
Texas         45678
New York      67890
Name: Population, dtype: int64

In [134]:
df = pop.unstack() # convert to 2-dimensional DataFrame
df

Year         2000   2010
State                   
California  12345  23456
New York    56789  67890
Texas       34567  45678

In [135]:
df.stack() # convert 2-dimensional DataFrame to a hierarchically indexed Series

State       Year
California  2000    12345
            2010    23456
New York    2000    56789
            2010    67890
Texas       2000    34567
            2010    45678
dtype: int64

In [136]:
# Multiple Series
df = pd.DataFrame({'Total': pop, 'Under18': [2345, 3456, 4567, 5678, 6789, 7890]})
df

Total  Under18
State      Year                
California 2000  12345     2345
           2010  23456     3456
Texas      2000  34567     4567
           2010  45678     5678
New York   2000  56789     6789
           2010  67890     7890

In [137]:
f_u18 = df['Under18'] / df['Total']
f_u18

State       Year
California  2000    0.189955
            2010    0.147340
Texas       2000    0.132120
            2010    0.124305
New York    2000    0.119548
            2010    0.116217
dtype: float64

In [138]:
f_u18.unstack()

Year            2000      2010
State                         
California  0.189955  0.147340
New York    0.119548  0.116217
Texas       0.132120  0.124305

## Creating MultiIndex explicitly
You can create a MultiIndex object and give it to the `index` argument of a Series or DataFrame. There are 4 ways of creating MultiIndexes.

In [139]:
# From tuples
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [140]:
# From arrays
pd.MultiIndex.from_arrays([list('aabb'), [1, 2, 1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [141]:
# From a cross-product, when every first level has every second level
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [142]:
# Explicitly using `levels` and `labels` arguments to constructor
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
             labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

## Creating MuiltiIndexes implicitly
You can make Series and DataFrame compute a MultiIndex automatically

In [143]:
# From arrays
data = np.random.rand(4, 2)
pd.DataFrame(data,
            index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
            columns=['data1', 'data2'])

data1     data2
a 1  0.259991  0.440788
  2  0.527288  0.256136
b 1  0.036224  0.321507
  2  0.905827  0.783561

In [144]:
# From data, where the keys are tuples
pd.Series({('a', 1): 12345,
             ('a', 2): 23456,
             ('b', 1): 34567,
             ('b', 2): 45678})

a  1    12345
   2    23456
b  1    34567
   2    45678
dtype: int64

## MultiIndexed Columns

In [145]:
rows = pd.MultiIndex.from_product([[2010, 2011], [1, 2]], names=['Year', 'Visit#'])
cols = pd.MultiIndex.from_product([['Bob', 'Amy', 'Sue'], ['B.P.', 'Temp']], names=['Subject', 'Type'])

data = np.round(np.random.randn(4, 6), 1)
health_df = pd.DataFrame(data, index=rows, columns=cols)
health_df

Subject      Bob       Amy       Sue     
Type        B.P. Temp B.P. Temp B.P. Temp
Year Visit#                              
2010 1       0.9 -2.1  1.2  0.1 -0.7  0.4
     2       0.0 -1.7 -0.3  0.3 -1.0  1.0
2011 1      -0.1 -0.1 -0.8 -0.1 -2.2  0.2
     2      -0.6  0.1 -0.0 -0.3 -1.6  1.8

### Column Indexing

In [146]:
health_df['Bob']

Type         B.P.  Temp
Year Visit#            
2010 1        0.9  -2.1
     2        0.0  -1.7
2011 1       -0.1  -0.1
     2       -0.6   0.1

In [147]:
health_df['Amy', 'Temp']

Year  Visit#
2010  1         0.1
      2         0.3
2011  1        -0.1
      2        -0.3
Name: (Amy, Temp), dtype: float64

Tuples can be used too.

In [148]:
health_df[('Amy', 'Temp')]

Year  Visit#
2010  1         0.1
      2         0.3
2011  1        -0.1
      2        -0.3
Name: (Amy, Temp), dtype: float64

### Row Indexing
To index rows, `loc` or `iloc` must be used.  Top-level indexes can be specified directly.

In [149]:
health_df.loc[2010]

Subject  Bob       Amy       Sue     
Type    B.P. Temp B.P. Temp B.P. Temp
Visit#                               
1        0.9 -2.1  1.2  0.1 -0.7  0.4
2        0.0 -1.7 -0.3  0.3 -1.0  1.0

Multi-level indexes can be specified using tuples.

In [150]:
health_df.loc[(2010, 1)]

Subject  Type
Bob      B.P.    0.9
         Temp   -2.1
Amy      B.P.    1.2
         Temp    0.1
Sue      B.P.   -0.7
         Temp    0.4
Name: (2010, 1), dtype: float64

### Row and Column Indexing

In [151]:
health_df.loc[(2010, 1), 'Bob']

Type
B.P.    0.9
Temp   -2.1
Name: (2010, 1), dtype: float64

In [152]:
health_df.loc[(2010, 1), ('Amy', 'Temp')]

0.10000000000000001

## Slices with `loc`
For slices to work with `loc`, the rows or columns being sliced must be **ordered**.

Column slicing:

In [153]:
# health_df.loc[(2010, 1), 'Amy':] ## Will raise error.
health_df.sort_index(axis=1, inplace=True)
health_df

Subject      Amy       Bob       Sue     
Type        B.P. Temp B.P. Temp B.P. Temp
Year Visit#                              
2010 1       1.2  0.1  0.9 -2.1 -0.7  0.4
     2      -0.3  0.3  0.0 -1.7 -1.0  1.0
2011 1      -0.8 -0.1 -0.1 -0.1 -2.2  0.2
     2      -0.0 -0.3 -0.6  0.1 -1.6  1.8

In [154]:
health_df.loc[(2010, 1), 'Bob':] # Won't raise error now

Subject  Type
Bob      B.P.    0.9
         Temp   -2.1
Sue      B.P.   -0.7
         Temp    0.4
Name: (2010, 1), dtype: float64

In [155]:
health_df.loc[:, 'Bob']

Type         B.P.  Temp
Year Visit#            
2010 1        0.9  -2.1
     2        0.0  -1.7
2011 1       -0.1  -0.1
     2       -0.6   0.1

Second level slices need an explicit slice object, because creating slices in tuples leads to a syntax error.

In [156]:
# health_df.loc[(:, 1), 'Bob']  # (:, 1) => syntax error

In [157]:
idx = pd.IndexSlice
health_df.loc[idx[:, 1], 'Bob']

Type         B.P.  Temp
Year Visit#            
2010 1        0.9  -2.1
2011 1       -0.1  -0.1

In [158]:
idx = pd.IndexSlice
health_df.loc[idx[:, 1], idx[:, 'Temp']]

Subject      Amy  Bob  Sue
Type        Temp Temp Temp
Year Visit#               
2010 1       0.1 -2.1  0.4
2011 1      -0.1 -0.1  0.2

## Slices with `iloc`
Same as `loc`, except that all indices are integers.

Examplles: TODO.

## Creating MultiIndexes from 2-dimensional DataFrames

In [159]:
# A 2-D DataFrame, such as one you'd get by reading a CSV file
df = pd.DataFrame([['California', 2000, 12345],
                  ['California', 2010, 23456],
                  ['New York', 2000, 34567],
                  ['New York', 2010, 45678],
                  ['Texas', 2000, 56789],
                  ['Texas', 2010, 67890]],
                 columns=['State', 'Year', 'Population'])
df

State  Year  Population
0  California  2000       12345
1  California  2010       23456
2    New York  2000       34567
3    New York  2010       45678
4       Texas  2000       56789
5       Texas  2010       67890

In [160]:
# Convert to MultiIndex
df.set_index(['State', 'Year'], inplace=True)
df

Population
State      Year            
California 2000       12345
           2010       23456
New York   2000       34567
           2010       45678
Texas      2000       56789
           2010       67890

In [161]:
# And back
df.reset_index()

State  Year  Population
0  California  2000       12345
1  California  2010       23456
2    New York  2000       34567
3    New York  2010       45678
4       Texas  2000       56789
5       Texas  2010       67890

## Simple Data Aggregation
Pandas' `Series` and `DataFrame` objects have numerours methods to compute aggregates, such as the sum, min, max, of quantities.  All the aggregations available in NumPy are also available in Pandas.

Given a `DataFrame`:

In [169]:
health_df

Subject      Amy       Bob       Sue     
Type        B.P. Temp B.P. Temp B.P. Temp
Year Visit#                              
2010 1       1.2  0.1  0.9 -2.1 -0.7  0.4
     2      -0.3  0.3  0.0 -1.7 -1.0  1.0
2011 1      -0.8 -0.1 -0.1 -0.1 -2.2  0.2
     2      -0.0 -0.3 -0.6  0.1 -1.6  1.8

The `describe()` method gives several important aggregations in one shot, to give us a feel of the data.

In [170]:
health_df.describe()

Subject    Amy                   Bob                 Sue          
Type      B.P.          Temp    B.P.      Temp      B.P.      Temp
count    4.000  4.000000e+00  4.0000  4.000000  4.000000  4.000000
mean     0.025  1.387779e-17  0.0500 -0.950000 -1.375000  0.850000
std      0.850  2.581989e-01  0.6245  1.112055  0.665207  0.718795
min     -0.800 -3.000000e-01 -0.6000 -2.100000 -2.200000  0.200000
25%     -0.425 -1.500000e-01 -0.2250 -1.800000 -1.750000  0.350000
50%     -0.150  0.000000e+00 -0.0500 -0.900000 -1.300000  0.700000
75%      0.300  1.500000e-01  0.2250 -0.050000 -0.925000  1.200000
max      1.200  3.000000e-01  0.9000  0.100000 -0.700000  1.800000

We can compute individual aggregations:

In [172]:
health_df.mean()

Subject  Type
Amy      B.P.    2.500000e-02
         Temp    1.387779e-17
Bob      B.P.    5.000000e-02
         Temp   -9.500000e-01
Sue      B.P.   -1.375000e+00
         Temp    8.500000e-01
dtype: float64

### Choosing the level in hierarchical indexes
With hierarchical indexes, we can choose what level to preserve (aggregating others).

In [163]:
health_df.mean(level='Visit#')

Subject   Amy       Bob        Sue     
Type     B.P. Temp B.P. Temp  B.P. Temp
Visit#                                 
1        0.20  0.0  0.4 -1.1 -1.45  0.3
2       -0.15  0.0 -0.3 -0.8 -1.30  1.4

In [164]:
health_df.mean(level='Year')

Subject   Amy        Bob        Sue     
Type     B.P. Temp  B.P. Temp  B.P. Temp
Year                                    
2010     0.45  0.2  0.45 -1.9 -0.85  0.7
2011    -0.40 -0.2 -0.35  0.0 -1.90  1.0

We can specify the axis along which to apply the aggregation; we can also have successive aggregations.

In [165]:
health_df.mean(level='Year').mean(level='Type', axis=1)

Type      B.P.      Temp
Year                    
2010  0.016667 -0.333333
2011 -0.883333  0.266667

## Concatenation
We can concat two `DataFrame` or `Series` objects.

In [175]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1,2,3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4,5,6])
print(ser1); print(ser2); print(pd.concat([ser1, ser2]));

1    A
2    B
3    C
dtype: object
4    D
5    E
6    F
dtype: object
1    A
2    B
3    C
4    D
5    E
6    F
dtype: object


We can also concatenate `DataFrame` objects.

First, a convenience function:

In [177]:
# A function to generate DataFrames quickly
def make_df(cols, ind):
    """Quickly make a DataFrame for tests."""
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [178]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1); print(df2); print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


### Handling Duplicate Indices
Since Pandas indices are explicit, the indices of the objects to be concatenate may *overlap*.  The default behaviour of `concat` is to preserve the indices in specified order.

In [190]:
x = make_df('AB', [0, 1]); x

A   B
0  A0  B0
1  A1  B1

In [192]:
y = make_df('AB', [1, 2]); y

A   B
1  A1  B1
2  A2  B2

In [194]:
pd.concat([x, y]) # 1 repeated!

A   B
0  A0  B0
1  A1  B1
1  A1  B1
2  A2  B2

#### Catching duplicates as errors
We can tell Pandas to verify that the indices in the result do not overlap.

In [195]:
try:
    pd.concat([x, y], verify_integrity=True) # will raise ValueError
except ValueError as e:
    print("ValueError: ", e)

ValueError:  Indexes have overlapping values: [1]


#### Ignoring the specified indices
We can get Pandas to generate new integer indices in the result, ignoring the indices in the inputs.

In [196]:
pd.concat([x, y], ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A1  B1
3  A2  B2

#### Adding MultiIndex keys
We can ask Pandas to use hierarchically indexed results.  We do this by specifying labels for the input data sources using the `keys` option.  Pandas will then nest the indices of a data source under a top level index of the specified keys.

In [197]:
print(x); print(y); print(pd.concat([x, y], keys=['x', 'y']))

    A   B
0  A0  B0
1  A1  B1
    A   B
1  A1  B1
2  A2  B2
      A   B
x 0  A0  B0
  1  A1  B1
y 1  A1  B1
  2  A2  B2


### Handling different columns - concat with join
If the input `DataFrame` objects have different columns, the default behaviour of `concat` is to do an *outer*-join like operation, producing a result that has the union of columns. It will fill missing fields with `NaN` values.

In [198]:
df1 = make_df('ABC', [1,2]); df1

A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [199]:
df2 = make_df('BCD', [3,4]); df2

B   C   D
3  B3  C3  D3
4  B4  C4  D4

In [200]:
pd.concat([df1, df2])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

#### Using inner join
We can tell Pandas to keep only the columns that are common to both inputs; that is, do an *inner8*-join.

In [201]:
pd.concat([df1, df2], join='inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

#### Specifying the index of the columns explicitly
We can force Pandas to use a specific list of index objects.  Here, we specify the column indices of the first input.

In [206]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [207]:
pd.concat([df1, df2], join_axes=[df1.columns])

A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

### `append` as a shortcut to `concat`
Concatenating dataframes and series in the default way is common, so `append` is a shortcut for that.  `append` does not modify the original objects but creates a new one.  It is less efficient that `concat` especially when concatenating multiple objects.

In [213]:
df1 = make_df('AB', [0, 1])
df2 = make_df('AB', [1, 2])
df1.append(df2, ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A1  B1
3  A2  B2

## Merges
Pandas offers high-performance in-memory join and merge operations, like database `JOIN`s, via the `pd.merge` function.

In [240]:
df1 = pd.DataFrame({'employee': ['Bob', 'Lisa', 'George', 'Sue'],
                    'department': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df1

department employee
0   Accounting      Bob
1  Engineering     Lisa
2  Engineering   George
3           HR      Sue

In [234]:
df2 = pd.DataFrame({'name': ['Bob', 'George', 'Sue', 'Lisa'],
                    'hire_date': [2001, 2010, 2009, 1005]})
df2

hire_date    name
0       2001     Bob
1       2010  George
2       2009     Sue
3       1005    Lisa

In [237]:
df3 = pd.DataFrame({'department': ['Accounting', 'Engineering', 'HR'], 
                   'supervisor': ['Alex', 'Guido', 'Carla']})
df3

department supervisor
0   Accounting       Alex
1  Engineering      Guido
2           HR      Carla

In [236]:
df4 = pd.DataFrame({'department': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR'],
                   'skill': ['Math', 'Excel', 'Excel', 'Programming', 'organization']})
df4

department         skill
0   Accounting          Math
1   Accounting         Excel
2  Engineering         Excel
3  Engineering   Programming
4           HR  organization

### One-to-one joins
This is the simplest case:

In [230]:
df1.merge(df2, left_on='employee', right_on='name')

employee        group  hire_date    name
0      Bob   Accounting       2001     Bob
1     Lisa  Engineering       1005    Lisa
2   George  Engineering       2010  George
3      Sue           HR       2009     Sue

We can get rid of the redundant column.

In [232]:
df1.merge(df2, left_on='employee', right_on='name').drop('name', axis=1)

employee        group  hire_date
0      Bob   Accounting       2001
1     Lisa  Engineering       1005
2   George  Engineering       2010
3      Sue           HR       2009

### One-to-Many joins
When one or the other data frame contains duplicate column values for the key column. Note also that Pandas automatically detect columns with the same name in both `DataFrame`s and uses them as the key column.

In [238]:
df1.merge(df3)

department employee supervisor
0   Accounting      Bob       Alex
1  Engineering     Lisa      Guido
2  Engineering   George      Guido
3           HR      Sue      Carla

### Many-to-Many joins
When key columns in both inputs contain duplicate values, we get a many-to-many join.

In [241]:
df1.merge(df4)

department employee         skill
0   Accounting      Bob          Math
1   Accounting      Bob         Excel
2  Engineering     Lisa         Excel
3  Engineering     Lisa   Programming
4  Engineering   George         Excel
5  Engineering   George   Programming
6           HR      Sue  organization

### Joining on an index instead of column value
The first data frame could have been like this:

In [246]:
df1a = df1.set_index('employee'); df1a

department
employee             
Bob        Accounting
Lisa      Engineering
George    Engineering
Sue                HR

To join this to `df2`, we have to use indices on `df1` to match column values on `df2`.  We can use `left_index=True` (or `right_index=True`) to tell Pandas to use indices instead of column values for the left or right argument.

In [255]:
df1a.merge(df2, left_index=True, right_on='name')

department  hire_date    name
0   Accounting       2001     Bob
3  Engineering       1005    Lisa
1  Engineering       2010  George
2           HR       2009     Sue

In [257]:
# Or even
df2.merge(df1a, left_on='name', right_index=True).set_index('name')

hire_date   department
name                          
Bob          2001   Accounting
George       2010  Engineering
Sue          2009           HR
Lisa         1005  Engineering

#### When both inputs are keyed on the indices
If both arguments are to be joined by their indices, we need to specify both `left_index` and `right_index` as `True`.  The `join` method is a short hand for this.

In [258]:
df2a = df2.set_index('name'); df2a

hire_date
name             
Bob          2001
George       2010
Sue          2009
Lisa         1005

In [260]:
df1a.merge(df2a, left_index=True, right_index=True)

department  hire_date
Bob      Accounting       2001
Lisa    Engineering       1005
George  Engineering       2010
Sue              HR       2009

**Using `join`**:

In [279]:
df1a.join(df2a)

department  hire_date
employee                        
Bob        Accounting       2001
Lisa      Engineering       1005
George    Engineering       2010
Sue                HR       2009

### Inner, Outer, Left and Right joins
When the two inputs have some missing values in the columns to be joined, it becomes important to specify how to handle missing values using the `how` keyword, which takes the values `outer`, `inner`, `left`, `right`.

In [261]:
df6 = pd.DataFrame({'name': ['Mary', 'Joseph', 'Peter'],
                   'food': ['Bread', 'Cheese', 'Fish']})
df6

food    name
0   Bread    Mary
1  Cheese  Joseph
2    Fish   Peter

In [266]:
df7 = pd.DataFrame({'name': ['Mary', 'Joseph', 'Paul'],
                   'drink': ['Wine', 'Beer', 'Mead']})
df7

drink    name
0  Wine    Mary
1  Beer  Joseph
2  Mead    Paul

In [267]:
df6.merge(df7) # default how=inner

food    name drink
0   Bread    Mary  Wine
1  Cheese  Joseph  Beer

In [268]:
df6.merge(df7, how='outer')

food    name drink
0   Bread    Mary  Wine
1  Cheese  Joseph  Beer
2    Fish   Peter   NaN
3     NaN    Paul  Mead

In [269]:
df6.merge(df7, how='left')

food    name drink
0   Bread    Mary  Wine
1  Cheese  Joseph  Beer
2    Fish   Peter   NaN

In [270]:
df6.merge(df7, how='right')

food    name drink
0   Bread    Mary  Wine
1  Cheese  Joseph  Beer
2     NaN    Paul  Mead

### Overlapping column names
When the two inputs have columns with the conflicting names (that is, the columns have different meanings but happen to have the same name), you can ask Pandas to generate unique column names using the `suffixes` option to `merge`.

Also, since more than one column now has the same name in the inputs, we have to specify the name of the key column to join on.  (By default Pandas will use a composite key of all columns that have name in each input.)

In [274]:
df8 = pd.DataFrame({'name': ['Mary', 'Joseph', 'Peter'],
                   'likes': ['Bread', 'Cheese', 'Fish']})
df8

likes    name
0   Bread    Mary
1  Cheese  Joseph
2    Fish   Peter

In [275]:
df9 = pd.DataFrame({'name': ['Mary', 'Joseph', 'Paul'],
                   'likes': ['Wine', 'Beer', 'Mead']})
df9

likes    name
0  Wine    Mary
1  Beer  Joseph
2  Mead    Paul

In [278]:
df8.merge(df9, on='name', suffixes=['_eat', '_drink'])

likes_eat    name likes_drink
0     Bread    Mary        Wine
1    Cheese  Joseph        Beer

## GroupBy: Aggregation, Filtering, Transform and grouping

In [282]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [283]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [292]:
decade = 10 * (planets['year'] // 10)
decade = decade.astype('str') + "s"
decade.name = 'decade'
planets.groupby(['method', decade])['number'].sum().unstack().fillna(0)

decade                         1980s  1990s  2000s  2010s
method                                                   
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0